name: Quickstart Bug Report
description: File a report to help us improve this sample application.
title: "[Bug]: "
labels: [bug]
assignees:
  - evansims
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve this sample application!
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: sdk
    attributes:
      label: SDK Version
      description: What version of our PHP SDK are you running? (`die(\Auth0\SDK\Auth0::VERSION);` within your application.)
      options:
        - 8.x
        - 7.x
    validations:
      required: true
  - type: dropdown
    id: php
    attributes:
      label: PHP Version
      description: What version of PHP are you running? `php -v`
      options:
        - PHP 8.0
        - PHP 7.4
        - PHP 7.3
    validations:
      required: true
  - type: dropdown
    id: composer
    attributes:
      label: Composer Version
      description: What version of Composer are you running? `composer -v`
      options:
        - 2.x
        - 1.x
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: I confirm this is a bug report
      description: General questions should be posted on the [Auth0 Community](https://community.auth0.com/)
      options:
        - label: I confirm this is a bug report
          required: true
