name: Quickstart Feature Request
description: File a feature request to help us take this sample application to the next level.
title: "[Feature Request]: "
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve this sample application!
  - type: textarea
    id: feature-description
    attributes:
      label: What should be added?
      description: How do you think this feature will improve the experience for newcomers to the Auth0 PHP SDK?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I confirm this is a feature request
      description: General questions should be posted on the [Auth0 Community](https://community.auth0.com/)
      options:
        - label: I confirm this is a feature request
          required: true
